openapi: 3.0.0
info:
  title: OpenCart API Module - Заказы
  description: REST API для управления заказами в OpenCart.
  version: 1.0.0
servers:
  - url: http://your-opencart-site.com
    description: Основной сервер OpenCart

paths:
  /api/orders:
    get:
      summary: Получить список заказов
      tags:
        - Заказы
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              example:
                - order_id: 1
                  firstname: "John"
                  lastname: "Doe"
                  email: "john.doe@example.com"
                  total: 100.00
        '401':
          description: Не авторизован

  /api/orders/{order_id}:
    get:
      summary: Получить заказ по ID
      tags:
        - Заказы
      security:
        - ApiKeyAuth: []
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              example:
                order_id: 1
                firstname: "John"
                lastname: "Doe"
                email: "john.doe@example.com"
                total: 100.00
                products:
                  - product_id: 42
                    name: "Example Product"
                    quantity: 2
                    price: 50.00
        '401':
          description: Не авторизован

  /api/orders/create:
    post:
      summary: Создать заказ
      tags:
        - Заказы
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order:
                  type: object
                  properties:
                    firstname:
                      type: string
                      example: "John"
                    lastname:
                      type: string
                      example: "Doe"
                    email:
                      type: string
                      example: "john.doe@example.com"
                    telephone:
                      type: string
                      example: "123456789"
                    shipping_address_1:
                      type: string
                      example: "123 Main Street"
                    shipping_city:
                      type: string
                      example: "New York"
                    shipping_country:
                      type: string
                      example: "United States"
                    shipping_method:
                      type: string
                      example: "Flat Rate"
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: integer
                        example: 42
                      name:
                        type: string
                        example: "Example Product"
                      quantity:
                        type: integer
                        example: 2
                      price:
                        type: number
                        example: 50.00
                      total:
                        type: number
                        example: 100.00
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              example:
                order_id: 1
        '401':
          description: Не авторизован

  /api/orders/update/{order_id}:
    put:
      summary: Обновить заказ
      tags:
        - Заказы
      security:
        - ApiKeyAuth: []
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order:
                  type: object
                  properties:
                    firstname:
                      type: string
                      example: "John"
                    lastname:
                      type: string
                      example: "Doe"
                    email:
                      type: string
                      example: "john.doe@example.com"
                    telephone:
                      type: string
                      example: "123456789"
                    shipping_method:
                      type: string
                      example: "Express Shipping"
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: integer
                        example: 42
                      name:
                        type: string
                        example: "Updated Product"
                      quantity:
                        type: integer
                        example: 3
                      price:
                        type: number
                        example: 60.00
                      total:
                        type: number
                        example: 180.00
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              example:
                status: "success"
        '401':
          description: Не авторизован

  /api/orders/delete/{order_id}:
    delete:
      summary: Удалить заказ
      tags:
        - Заказы
      security:
        - ApiKeyAuth: []
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              example:
                status: "success"
        '401':
          description: Не авторизован

securitySchemes:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Client-ID